### ISSUE TITLE
安装失败，卡在清空目录

### ISSUE THREAD

**Issue by ratsafalig** [sillycross/dts#166]
一直卡在这一步
![1](https://user-images.githubusercontent.com/33503055/55175390-2a7b4780-51ba-11e9-9702-5ab2a135a450.jpg)
进入主界面的话是这样
![2](https://user-images.githubusercontent.com/33503055/55175396-2d763800-51ba-11e9-83c6-9ee6b011c09b.jpg)
环境是php73+mariadb

**Comment by ratsafalig** [comment]
如果主界面登陆出现这个错误
![1](https://user-images.githubusercontent.com/33503055/55177163-885d5e80-51bd-11e9-8a1f-81224fab69d1.jpg)

**Comment by nahakyuu** [comment]
检查下是否存在 ./gamedata/tmp/replay 文件夹

**Comment by ratsafalig** [comment]
。。不存在。。创建一个吗？。。好吧
